### ISSUE TITLE
Add IBC support to multi-test

### ISSUE THREAD

**Issue by ethanfrey** [CosmWasm/cw-multi-test#1]
We now have support for Custom Msg and Queries, and an easy way to plug in Staking and Distribution support. (#266)

One missing feature is being able to simulate IBC calls between 2 apps. This will require significant changes to the App structure and some coordinator that controls 2 apps. Rather than hide this as a checkbox, it makes sense to pull it into a full-blown issue to discuss.

**Comment by DariuszDepta** [comment]
I am closing this issue, as IBC support will be implemented as in #184.
