### ISSUE TITLE
addr_humanize to determinate Instantiate2 address fail

### ISSUE THREAD

**Issue by Rhaki** [CosmWasm/cw-multi-test#113]
Using `cw-multi-test` with `Instantiate2` Msg, in order to determinate the address of the new contract init by another contract, `deps.api.addr_humanize(&canonical_addr)` need to be queried. `deps.api` is provided by the class `App`, and by defualt is `MockApi` from `cosmwasm-std`. The problem is that the `addr_humanize` function on `MockApi` implemented into the trait `Api`, perform this:

```rust
fn addr_humanize(&self, canonical: &CanonicalAddr) -> StdResult<Addr> {
  if canonical.len() != self.canonical_length {
      return Err(StdError::generic_err(
          "Invalid input: canonical address length not correct",
      ));
  }
  ...
```
but `canonical.len() != self.canonical_length` is true since the address of the contract that is instantiating the new one has been created by the `App` and usually it has a name like `contract1`, resulting the `CanonicalAddr` of the address that is beeing instantiated to not be equal to the `self.canonical_length` that is setted as `const CANONICAL_LENGTH: usize = 90`

**Comment by DariuszDepta** [comment]
Hi @Rhaki,
I guess using `MockApiBech32` from `cw-multi-test` should solve this problem. Till version 2.0 of `cosmwasm-std`, there is in fact some inconsistency in MockApi, but it will be fixed and aligned in v2.0 of `cosmwasm-std` as mentioned.
Please consult this article: https://medium.com/cosmwasm/addresses-in-cosmwasm-multitest-68207ae845e6 to find out how to configure Bech32 addresses - these should help to solve your issue (I guess).
If not, please do not hesitate to share a link to your test case and we will try to help.

**Comment by DariuszDepta** [comment]
Hi @Rhaki, can we help in any way, or we can close this issue?

**Comment by Rhaki** [comment]
Hi. Sorry for long delay. Yes you can close di issue. It has been solved with generator api
