### ISSUE TITLE
Instantiate2 address generator conflict

### ISSUE THREAD

**Issue by Kayanski** [CosmWasm/cw-multi-test#122]
# Core Issue
The current Instantiate2 address generator (found here : https://github.com/CosmWasm/cw-multi-test/blob/main/src/addresses.rs#L123) doesn't take into account other fields than the salt.

# Fail Example
If in a script 2 contracts get created via `instantiate2` with the same salt from 2 different creators, the second address creation will fail or override the existent one.

# Possible solution
The creator should be taken into account when creating an instantiate2 address. We could use the following code snippet. Just like some actual on-chain tokenfactory use:

```rust 
format!(
            "contract/{}/{}",
            creator,
            HexBinary::from(salt).to_hex()
        ))
```

**Comment by DariuszDepta** [comment]
Hi @Kayanski,

The idea behind this simplistic implementation was to provide a solution that:
1. Is similar to already existing implementation of generating "unpredictable" addresses.
2. Is so simple, that makes no doubts what comes out as a "predictable" address.

The simplistic implementation of "unpredictable" addresses uses only contract instance number, so in fact, in tests, unpredictable addresses are also fully predictable like `contract0`, `contract1`, `contract2` and so on.
The same way is the "predicatble" address generator constructed, using just single attribute - the **salt**. So "predictable" addresses are fully predictable when the _salt is not changed_. And that was the intent while providing this uncomplicated and simplistic implementation named **`SimpleAddressGenerator`**.

I understand, that more advanced users could require more sophisticated solution, that simulates the real blockchain behaviour when it comes to contract address generation, and this is also provided as described in [this article](https://medium.com/cosmwasm/addresses-in-cosmwasm-multitest-68207ae845e6).

We can of course open a discussion what kind of addresses the default address generator in **MultiTest** should produce, and I am open to hear multiple ideas from multiple blockchain users. I am eager to implement the solution that satisfies the majority, giving the minority a chance to select another solution they need.

I am closing this issue but feel free to comment on it.

**Comment by Kayanski** [comment]
I don't understand your argument there. Having the sender address in there doesn't change anything to the the predictability of the address and makes it even clearer that the contract was generated using a predictable address pattern (for instance if you choose salt =`0`, you get potential simpler confilcts. 

Anyway, I respect the decision of course without understanding fully where it comes from. Such address conflicts could happen so easily in test scenarios.

**Comment by DariuszDepta** [comment]
I am taking a look again. Having conflicts in such a simple case is not a pleasant situation.

**Comment by Kayanski** [comment]
I'm sorry, didn't want to be conflicting on this

**Comment by DariuszDepta** [comment]
No, no, it's ok, I meant the conflicting contract addresses but it could really be interpreted quite differently :-)
I have prepared a fix for your issue. I hope this will avoid any potential conflicts when predictable contract address are generated. Please take a look at #125 and let me know if this solves your case.

Thanks for reporting this issue: :1st_place_medal:

**Comment by Kayanski** [comment]
This is good, thank you, less conflicts yeeaah !
