### ISSUE TITLE
instantiate_contract fails with "Generic error: Error decoding bech32"

### ISSUE THREAD

**Issue by maxmousse** [CosmWasm/cw-multi-test#169]
Hi everyone,

While following the cosmwasm book, I encounterd the next problem: When running `instantiate_contract` in tests, the call returns an error.
Here is a code sample:

```rust
    let addr = app
        .instantiate_contract(
            code_id,
            owner_addr,
            &InstantiateMsg {
                donation_denom: "uusd".to_owned(),
                fee_collector_addr: "fee_collector_addr".to_owned(),
                projects: vec![
                    ("project1".to_owned(), "creator_addr_1".to_owned()),
                    ("project2".to_owned(), "creator_addr_2".to_owned()),
                ],
            },
            &[],
            "Contract",
            None,
        )
        .unwrap();
```

And the resulting error:
```
called `Result::unwrap()` on an `Err` value: Error executing WasmMsg:
  sender: cosmwasm1fsgzj6t7udv8zhf6zj32mkqhcjcpv52yph5qsdcl0qt94jgdckqs2g053y
  Instantiate { admin: None, code_id: 1, msg: {"donation_denom":"uusd","fee_collector_addr":"fee_collector_addr","projects":[]}, funds: [], label: "Contract" }

Caused by:
    Generic error: Error decoding bech32
```

I was not able to found a solution, and I'm not even sure if that's a bug or if I'm missusing the `instantiate_contract` function.

Here is a reproduction repository: https://github.com/maxmousse/cosmwasm-test . Just run `cargo test` and the error should pop up.

If someone can points me in the right direction, I'm willing to submit a PR to eather fix this, or add some examples in the documentation ;)

**Comment by DariuszDepta** [comment]
Hi @maxmousse, please take a look at this: #165. We are currently working on making documentation better...

**Comment by DariuszDepta** [comment]
Hi @maxmousse!
Please take a look at the PR I prepared in your codebase: https://github.com/maxmousse/cosmwasm-test/pull/3.
Hopefully it clarifies all concerns and helps you in further development of your contract.
I am closing this issue, but feel free to reopen it if needed, or file a new one.
Kind Regards,
Darek

**Comment by maxmousse** [comment]
Hello @DariuszDepta, thanks a lot for your PR, it is very helpful and answer my questions!
