### ISSUE TITLE
Using `addr_make` inside `AppBuilder::build`

### ISSUE THREAD

**Issue by chipshort** [CosmWasm/cw-multi-test#188]
This came up in a PR for the cw-template repo: https://github.com/CosmWasm/cw-template/pull/158#discussion_r1639931420

Because the `init_fn` only receives a `&dyn Api`, one cannot call `api.addr_make` using that.
Should we expose the actual `ApiT` to `init_fn`? Or is there a better way?

**Comment by DariuszDepta** [comment]
Hey @chipshort and @Perelyn-sama, there is a PR #189 that addresses this issue. I'll be grateful for feedback.

**Comment by Perelyn-sama** [comment]
Hey @DariuszDepta, thanks for the great article again. 

I'll check out the PR you mentioned and send some feedback your way.🫡
