### ISSUE TITLE
Support multiple custom messages / queries

### ISSUE THREAD

**Issue by maurolacy** [CosmWasm/cw-multi-test#2]
Multitests relying on `TgradeApp` must now (since cw-plus 0.12.1) use `TgradeQuery`. Because `TgradeQuery` is defined at the app level.

This imposes some restrictions to our test code, in that we cannot in principle call contracts that don't implement the custom `TgradeQuery`.

There are some workarounds already, like the `TgradeWrapper::new_with_empty` constructor, and the associated `with_sudo/reply/migrate_empty` builder-like helpers.

It would simplify and generalise testing considerably if the message / query type could be specified at least at the contract level (i.e. in or as part of the `store_code` call). That would still require that all the entry points for that contract are of the same type. But, it will allow for easy heterogeneous "contracts with custom message" multi tests. And will be better suited for the future, in which we can have contracts with more than one custom message type (besides `Empty`).

Doing this could be daunting, though, as this custom type is currently associated to everything from app and deps to responses.

Related issues / comments:

- https://github.com/CosmWasm/cw-plus/pull/660#issuecomment-1043177477
- https://github.com/confio/tfi/pull/68
- https://github.com/confio/poe-contracts/pull/103#issue-1137254582
- https://github.com/confio/poe-contracts/pull/109

**Comment by ethanfrey** [comment]
> But, it will allow for easy heterogeneous "contracts with custom message" multi tests. And will be better suited for the future, in which we can have contracts with more than one custom message type (besides Empty).

In a real world situation (where the contract will be deployed), all contracts must use the blockchain's custom msg or Empty. You cannot have one contract that does `OsmosisQuery` and another that does `TgradeQuery` and a third with `StargazeQuery` in the same blockchain.

If we define one CustomMsg for the App and then auto-accept that or Empty, that would be an improvement.
Maybe we accept anything that implements `Into<CosmosMsg<C, Q>>` where `C` and `Q` are defined in the app. And in ContractWrapper we manage all the needed magic. This may need a few interesting trait implementations for Empty, but could accomplish some of what you wish

**Comment by rever96** [comment]
This is not solved...
I have the same problem.
My contract entry point have specific DepsMut<TerraQuery> and Deps<TerraQuery> (from classic-bindings)

in this example I can't pass the variable into store_code funct:
```rs
    let contract = ContractWrapper::new(execute, instantiate, query);
    let liquid_farm_contract: Box<(dyn Contract<Empty, TerraQuery> + 'static)> = Box::new(contract);

    let code_id = app.store_code(liquid_farm_contract);
```

the app is created with this funct:

```rs

pub fn mock_app() -> App {
    let api = MockApi::default();
    let env = mock_env();
    let bank = BankKeeper::new();
    let storage = MockStorage::new();

    let app = AppBuilder::new()
        .with_api(api)
        .with_block(env.block)
        .with_bank(bank)
        .with_storage(storage)
        .build(|_, _, _| {});
    app
}
```

**Comment by DariuszDepta** [comment]
Hi @rever96, could you share a repository where I could take a look at this test case?

**Comment by rever96** [comment]
Here it is https://github.com/rever96/TestGenericDeps
@DariuszDepta thanks.
I managed to make it more clean as possible

**Comment by DariuszDepta** [comment]
Hi @rever96, there is a PR that seems to work: https://github.com/rever96/TestGenericDeps/pull/1

**Comment by rever96** [comment]
thanks @DariuszDepta.
You solved the problem when App is simple type without needed custom modifications in any part.
for example I have this test app type that need to support the  `DepsMut<TerraQuery>`:
```rs

pub type WKApp<B, A, S, C, X, D, I, G, T> = Rc<
    RefCell<
        App<B, A, S, C, WasmKeeper<<C as Module>::ExecT, <C as Module>::QueryT>, X, D, I, G, T>,
    >,
>;

```

how to add correctly TerraQuery to make this works in instantiation of contract?

i also commented inside the pullrequet of the test repo i created.
