### ISSUE TITLE
Support `SetWithdrawAddress` DistributionMsg

### ISSUE THREAD

**Issue by JakeHartnell** [CosmWasm/cw-multi-test#20]
Was working on a payroll contract that uses this and discovered it wasn't supported by `cw-multi-test`. Received the error: `Unsupported distribution message`.

Relevant area of the code:
https://github.com/CosmWasm/cw-multi-test/blob/d3bb2cce8e135fe8a977dd99a0a63643fb3b8b31/src/staking.rs#L807

**Comment by DariuszDepta** [comment]
I am closing this issue while `SetWithdrawAddress` it was implemented in #23.
