### ISSUE TITLE
Better error loggin when a message execution fails

### ISSUE THREAD

**Issue by Kayanski** [CosmWasm/cw-multi-test#60]
The 3 lines here : https://github.com/CosmWasm/cw-multi-test/blob/main/src/wasm.rs#L210-L213, prevent error messages to propagate properly (especially for nested execution and replies to error messages). 

This makes it really difficult to find out what the error message is.

I understand that this mimic Contract execution and obscure error messages, but for dev purposes, is it possible to propagate errors without obfuscating them ?

Thank you for your concern :)

**Comment by DariuszDepta** [comment]
Hi @Kayanski,

There is a chain of errors returned, that can be simply printed in debug, e.g.:
```
println!("{:?}", err);
```
and produces full error report with the initial place where the error occured, similar to following:
```
Error executing WasmMsg:
sender: random
Execute { contract_addr: "contract0", msg: {"execute":{"contract_addr":"contract1","msg":"eyJleGVjdXRlIjp7ImNvbnRyYWN0X2FkZHIiOiJjb250cmFjdDIiLCJtc2ciOiJlMzA9IiwiZnVuZHMiOltdfX0=","funds":[]}}, funds: [] }

Caused by:
    0: error executing WasmMsg:
       sender: contract0
       Execute { contract_addr: "contract1", msg: {"execute":{"contract_addr":"contract2","msg":"e30=","funds":[]}}, funds: [] }
    1: error executing WasmMsg:
       sender: contract1
       Execute { contract_addr: "contract2", msg: {}, funds: [] }
    2: Generic error: Handle failed
```
You can check it in the App test, here:
https://github.com/CosmWasm/cw-multi-test/blob/main/src/app.rs#L3210-L3211

Let me know if it addresses your needs :-)

**Comment by Kayanski** [comment]
Hello, thanks for the quick reply ! Actually, what I am doing in my contract is returning the error as text to an acknowlegment function whoch sends back the result (this is en IBC implementation), so what's returned is only the error Display text and not debug. Because it's IBC obviously the function should not error. 

For now, I'm just commenting out the lines I quoted above for my needs, but as per your answer, I don't see a way of handling that better for now

**Comment by DariuszDepta** [comment]
Ok, so if the Display for such an error would contain the report I mentioned previously, then it would be satisfactory for you?

**Comment by Kayanski** [comment]
Yes that would be very good for my purposes ! Thank you. IBC is always complicated to handle, let's make it simple 🦾

**Comment by DariuszDepta** [comment]
Just to make it clearer for me, could you provide only the code snippet where you get the error and you convert it to text to place it in reply message, please?

**Comment by Kayanski** [comment]
Yes it's here : https://github.com/DA0-DA0/polytone/blob/main/contracts/main/voice/src/ibc.rs#L122C32-L122C32

**Comment by DariuszDepta** [comment]
Hello @Kayanski!

Could you run your tests using Multi Test from the branch **better-error-logging**, just to verify if it reports your errors more precisely?

Thanks in advance.

**Comment by Kayanski** [comment]
Hello ! This is perfect ! I now have something like this, which is expected and simpler to debug : 

```json
{"fatal_error":"Error executing WasmMsg:\n  sender: contract9\n  Execute { contract_addr: \"contract9\", msg: {\"rx\":{\"connection_id\":\"connection-0\",\"counterparty_port\":\"wasm.contract8\",\"data\":\"eyJzZW5kZXIiOiJjb250cmFjdDQiLCJtc2ciOnsiZXhlY3V0ZSI6eyJtc2dzIjpbXX19fQ==\"}}, funds: [] }\n\nCaused by:\n    Generic error: Invalid input: canonical address length not correct"}
```
Thank you for this fix !
